name: Test suite

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        fc:
          - gfortran
          - ifx
        debug:
          - no
          - yes
        mpi:
          - no
          - yes
        exclude:
          - fc: ifx
            mpi: yes

    name: compile (${{ matrix.fc }} ${{ matrix.mpi == 'yes' && 'MPI' || 'serial' }}${{ matrix.debug == 'yes' && ' debug' || '' }})

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-intel-oneapi
      if: matrix.fc == 'ifx'

    - name: Set up OpenMPI
      if: matrix.mpi == 'yes'
      run: sudo apt-get install -y openmpi-bin libopenmpi-dev

    - name: Compile
      working-directory: ./work
      run: |
        set -o pipefail
        make ${{ matrix.debug == 'yes' && 'debug' || '' }} | tee compile.log
      env:
        FC: ${{ matrix.fc }}
        MPI: ${{ matrix.mpi }}

    - name: Save binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.fc }}-debug_${{ matrix.debug }}-mpi_${{ matrix.mpi }}
        path: ./work/hormone

    - name: Save compile log as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.fc }}-debug_${{ matrix.debug }}-mpi_${{ matrix.mpi }}-compile-log
        path: ./work/compile.log

  test:
    needs: compile
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        fc:
          - gfortran
          - ifx
        debug:
          - no
          - yes
        mpi:
          - no
          - yes
        test:
          - sodshock_x
          - sodshock_y
          - sodshock_z
          - briowushock_x
          - briowushock_y
          - briowushock_z
          - orszagtang_xy
          - orszagtang_yz
          - orszagtang_xz
          - sedov_default
          - KHinstability
          - star_sph
          - polytrope
          - iotest
        flat:
          - no
          - yes
        exclude:
          - fc: ifx
            mpi: yes
          - test: polytrope
            flat: no
          # star_sph uses MICCG init, which is not compatible with MPI
          - test: star_sph
            mpi: yes

    name: ${{ matrix.test }} (${{ matrix.fc }} ${{ matrix.mpi == 'yes' && 'MPI' || 'serial' }}${{ matrix.debug == 'yes' && ' debug' || '' }}${{ matrix.flat == 'yes' && ' flat' || '' }})

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-intel-oneapi
      if: matrix.fc == 'ifx'

    - name: Set up OpenMPI
      if: matrix.mpi == 'yes'
      run: sudo apt-get install -y openmpi-bin libopenmpi-dev

    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.fc }}-debug_${{ matrix.debug }}-mpi_${{ matrix.mpi }}
        path: ./work

    - name: Set executable permissions for binary
      run: chmod +x ./work/hormone

    - name: Update startfile
      working-directory: ./work
      run: sed -i "s/sodshock_x/${{ matrix.test }}/g" startfile

    - name: Remove "test" after test name if doing iotest
      if: matrix.test == 'iotest'
      working-directory: ./work
      run: sed -i "s/iotest test/iotest/g" startfile

    - name: Flat reconstruction switch
      if: matrix.flat == 'yes'
      working-directory: ./para
      # If flux_limiter is specified, replace it with "flat", otherwise add the option
      run: |
        if grep -q "flux_limiter=" parameters_${{ matrix.test }}; then
          sed -i "s/flux_limiter='[^']*'/flux_limiter='flat'/" parameters_${{ matrix.test }}
        else
          sed -i "s/&simucon/\&simucon flux_limiter='flat'/" parameters_${{ matrix.test }}
        fi
        cat parameters_${{ matrix.test }}

    - name: Run test
      working-directory: ./work
      run: |
        if [[ "${{ matrix.mpi }}" == "yes" ]]; then
          mpirun -np 2 --oversubscribe ./hormone
        else
          ./hormone
        fi

  compiler-warnings:
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fc:
          - gfortran
        debug:
          - yes
        mpi:
          - no
          - yes

    name: warnings (${{ matrix.fc }} ${{ matrix.mpi == 'yes' && 'MPI' || 'serial' }}${{ matrix.debug == 'yes' && ' debug' || '' }})

    steps:
    - uses: actions/checkout@v4

    - name: Download compile log
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.fc }}-debug_${{ matrix.debug }}-mpi_${{ matrix.mpi }}-compile-log

    - name: Check for compiler warnings
      run: |
        if grep -q "Warning: " ./work/compile.log; then
          cat ./work/compile.log
          exit 1
        else
          echo "No compiler warnings found"
        fi

  # Gather results into a dummy job that will fail if the previous job fails
  gather_results:
    if: always()
    needs:
    - test

    # This name matches the branch protection requirement
    name: test

    runs-on: ubuntu-latest

    steps:
    - name: Check all tests
      run: |
        if [[ "${{ needs.test.result }}" == "success" ]]; then
          echo "All tests succeeded"
        else
          echo "At least one test failed"
          exit 1
        fi
